import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MyThemeProvider } from "./components/providers/MyThemeProvider";
import { ModuloProvider } from "./lib/contexts/ModulosContext";
import { PremiumProvider } from "./lib/contexts/PremiumContext";
import { PremiumAuthProvider } from "./lib/contexts/PremiumAuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "ZUNSteps",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <MyThemeProvider>
        <ModuloProvider>
          <PremiumAuthProvider>
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
              {children}
            </body>
          </PremiumAuthProvider>
        </ModuloProvider>
      </MyThemeProvider>
    </html>
  );
}
