import "./globals.css";
import { MyThemeProvider } from "./components/providers/MyThemeProvider";
import { ModuloProvider } from "./lib/contexts/ModulosContext";
import { PremiumProvider } from "./lib/contexts/PremiumContext";
import { PremiumAuthProvider } from "./lib/contexts/PremiumAuthContext";

export const metadata = {
  title: "ZUNSteps",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <MyThemeProvider>
        <ModuloProvider>
          <PremiumAuthProvider>
            <body>
              {children}
            </body>
          </PremiumAuthProvider>
        </ModuloProvider>
      </MyThemeProvider>
    </html>
  );
}
